const routes = {
  mainStack: {
    auth: 'AuthNavigator',
    main: 'MainNavigator',
  },
  navigator: {
    auth: 'Auth',
    tab: 'Tab',
  },
  tab: {
    home: 'HomeScreen',
    records: 'records',
    otherrecord: 'otherrecord',
    profile: 'profile',
    addrecords: 'addrecords',
    vehicles: 'vehicles',
  },
  auth: {
    AppStarter: 'AppStarter',
    welcome: 'WelcomeScreen',
    login: 'LoginScreen',
    signup: 'SignupScreen',
    forgot: 'ForgotPassword',
    genderSelect: 'GenderSelection',
    age: 'AgeCreationScreen',
    height: 'HeightCreationScreen',
    weight: 'WeightCreationScreen',
    payment: 'Payment',
    subscription: 'Subscription',
    otp: 'VerifyOtp ',
    resetPassword: 'ResetPassword ',
  },
  main: {
    AppStarter: 'AppStarter',
    setting: 'SettingScreen',
    myProfile: 'MyProfile',
    createdraft: 'CreateDraft',
    editProfile: 'EditProfile',
    changePassword: 'ChangePasswordScreen',
    contactUs: 'ContactUsScreen',
    mypurchase: 'MyPurchaseScreen',
    subscriptionplan: 'SubscriptionPlanScreen',
    paymentDetails: 'PaymentDetailsScreen',
    privacyPolicy: 'PrivacyPolicyScreen',
    termAndConditions: 'TermAndConditionsScreen',
    addVehicles: 'AddVehicles',
    addVehicleSubCategory: 'AddVehicleSubCategory',
    addVehicleDetails: 'AddVehicleDetails',
    vehicleDetails: 'VehicleDetails',
    vehicleAutoPart: 'VehicleAutoParts',
    notification: 'NotificationScreen',
    autoPartsDetails: 'AutoPartsDetails',
    repairsdetails: 'RepairsDetailsScreen',
    addautopartrecord: 'AddAutopartRecord',
    addrepairrecord: 'AddRepairRecord',
    addastore: 'Addastore',
    addnewseller: 'AddNewSeller',
    addnewmechanic: 'AddNewMechanic',
    editautoparts: 'EditAutoparts',
    editcustomrecords: 'EditCustomRecords',
    editrepairrecord: 'EditRepairRecord',
    editvechile: 'EditVechile',
    otherrecord: 'OtherRecord',
    vehiclehistory: 'VehicleHistory',
    addgasrecord: 'AddGasRecord',
    editgasrecord: 'EditGasRecord',
    addaccidentrecord: 'AddAccidentRecord',
    editaccidentrecord: 'EditAccidentRecord',
    addmaintenancerecord: 'AddMaintenanceRecord',
    editmaintenancerecord: 'EditMaintenanceRecord',
    addtravelrecord: 'AddTravelRecord',
    edittravelrecord: 'EditTravelRecord',
    addheavyequipmentrecord: 'AddHeavyEquipmentRecord',
    editheavyequipmentrecord: 'EditHeavyEquipmentRecord',
    addhomerecord: 'AddHomeRecord',
    edithomerecord: 'EditHomeRecord',
    addsmallequipmentrecord: 'AddSmallEquipmentRecord',
    editsmallequipmentrecord: 'EditSmallEquipmentRecord',
    addtoolrecord: 'AddToolRecord',
    edittoolrecord: 'EditToolRecord',
    addpetrecord: 'AddPetRecord',
    editpetrecord: 'EditPetRecord',
    addvetrecordforpet: 'AddVetRecordForPet',
    editvetrecordforpet: 'EditVetRecordForPet',
    addcustomrecord: 'AddCustomRecord',
    addDynamicCustomRecords: 'AddDynamicCustomRecords',
    draftdetails: 'DraftDetails',
    expensedetails: 'ExpenseDetails',
    editcustomrecordscategory: 'EditCustomRecordsCategory',
    vehicleMaintenanceDetails: 'VehicleMaintenanceDetails',
    testScreen: 'TestScreen',
    AddPart: 'AddPart'

    // Habbit Tracker Screen
  },

  plan: {},
};

export default routes;
